FROM python:3.11-slim

WORKDIR /app

RUN pip install --no-cache-dir \
    python-telegram-bot==21.* \
    asyncpg \
    aiokafka \
    nest_asyncio

COPY telegram_bot_kafka.py .

CMD ["python", "telegram_bot_kafka.py"]
