-- University Telegram Bot


CREATE TYPE semester_type     AS ENUM ('Fall', 'Spring', 'Summer');
CREATE TYPE session_kind      AS ENUM ('Lecture', 'Section', 'Lab');
CREATE TYPE week_day          AS ENUM ('Sunday','Monday','Tuesday','Wednesday',
                                       'Thursday','Friday','Saturday');
CREATE TYPE attendance_status AS ENUM ('Present','Absent','Late','Excused');
CREATE TYPE gender_type       AS ENUM ('Male','Female','Other');
CREATE TYPE grade_type        AS ENUM ('A+','A','A-','B+','B','B-',
                                       'C+','C','C-','D+','D','F','W','I','P');




CREATE OR REPLACE FUNCTION fn_touch_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.Updated_At = NOW();
    RETURN NEW;
END;
$$;


-- SECTION 2 — UNIVERSITY HIERARCHY

CREATE TABLE Universities (
    University_Id       INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    University_Name     VARCHAR(100) NOT NULL,
    University_Location VARCHAR(200),
    Created_At          TIMESTAMPTZ  DEFAULT NOW(),
    Updated_At          TIMESTAMPTZ  DEFAULT NOW()
);
CREATE TRIGGER trg_universities_upd
    BEFORE UPDATE ON Universities
    FOR EACH ROW EXECUTE FUNCTION fn_touch_updated_at();


CREATE TABLE Faculties (
    Faculty_Id       INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    University_Id    INT         NOT NULL REFERENCES Universities(University_Id) ON DELETE RESTRICT,
    Faculty_Name     VARCHAR(100) NOT NULL,
    Faculty_Location VARCHAR(200),
    Created_At       TIMESTAMPTZ DEFAULT NOW(),
    Updated_At       TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_faculties_university ON Faculties(University_Id);
CREATE TRIGGER trg_faculties_upd
    BEFORE UPDATE ON Faculties
    FOR EACH ROW EXECUTE FUNCTION fn_touch_updated_at();


CREATE TABLE Departments (
    Department_Id   INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Faculty_Id      INT         NOT NULL REFERENCES Faculties(Faculty_Id) ON DELETE RESTRICT,
    Department_Name VARCHAR(100) NOT NULL,
    Created_At      TIMESTAMPTZ DEFAULT NOW(),
    Updated_At      TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_departments_faculty ON Departments(Faculty_Id);
CREATE TRIGGER trg_departments_upd
    BEFORE UPDATE ON Departments
    FOR EACH ROW EXECUTE FUNCTION fn_touch_updated_at();


-- SECTION 3 — PROFESSORS

CREATE TABLE Professors (
    Professor_Id    INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Department_Id   INT         NOT NULL REFERENCES Departments(Department_Id) ON DELETE RESTRICT,
    Professor_Name  VARCHAR(100) NOT NULL,
    Professor_Email VARCHAR(150) NOT NULL UNIQUE,
    Academic_Title  VARCHAR(100),
    Created_At      TIMESTAMPTZ DEFAULT NOW(),
    Updated_At      TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_professors_department ON Professors(Department_Id);
CREATE TRIGGER trg_professors_upd
    BEFORE UPDATE ON Professors
    FOR EACH ROW EXECUTE FUNCTION fn_touch_updated_at();


-- SECTION 4 — STUDENTS

CREATE TABLE Students (
    Student_Id        INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    National_Id       VARCHAR(20)  UNIQUE,            -- VARCHAR: national IDs can have leading zeros
    Student_Name      VARCHAR(100) NOT NULL,
    Phone             VARCHAR(20),                    -- VARCHAR: country codes, +20 prefix, etc.
    Address           VARCHAR(200),
    Birthdate         DATE,                           -- DATE: was incorrectly INT
    Gender            gender_type,
    Study_Year        SMALLINT CHECK (Study_Year BETWEEN 1 AND 7), -- student's year of study (1st–7th)
    Department_Id     INT          NOT NULL REFERENCES Departments(Department_Id) ON DELETE RESTRICT,
    Enrollment_Year   SMALLINT,                       -- calendar year of first enrollment
    Telegram_Id       BIGINT       UNIQUE,            -- BIGINT: Telegram IDs exceed INT range (~7–10 digits)
    Telegram_Username VARCHAR(100) UNIQUE,            -- Telegram max is 32 chars; 100 is a safe buffer
    Is_Active         BOOLEAN      NOT NULL DEFAULT TRUE, -- soft-delete flag
    Created_At        TIMESTAMPTZ  DEFAULT NOW(),
    Updated_At        TIMESTAMPTZ  DEFAULT NOW()
);

CREATE INDEX idx_students_telegram_id       ON Students(Telegram_Id);
CREATE INDEX idx_students_telegram_username ON Students(Telegram_Username);
CREATE INDEX idx_students_department        ON Students(Department_Id);
CREATE INDEX idx_students_national_id       ON Students(National_Id);
CREATE INDEX idx_students_active_tg         ON Students(Telegram_Id) WHERE Is_Active = TRUE;

CREATE TRIGGER trg_students_upd
    BEFORE UPDATE ON Students
    FOR EACH ROW EXECUTE FUNCTION fn_touch_updated_at();


-- SECTION 5 — COURSES

CREATE TABLE Courses (
    Course_Id     INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Department_Id INT          NOT NULL REFERENCES Departments(Department_Id) ON DELETE RESTRICT,
    Course_Code   VARCHAR(20)  UNIQUE,                -- e.g. CS301, MATH201 — added for display & lookup
    Course_Name   VARCHAR(100) NOT NULL,
    Credit_Hours  SMALLINT     CHECK (Credit_Hours BETWEEN 1 AND 6),
    Study_Year    SMALLINT,                           -- which year of study this course targets
    Semester      semester_type,
    Created_At    TIMESTAMPTZ  DEFAULT NOW(),
    Updated_At    TIMESTAMPTZ  DEFAULT NOW()
);
CREATE INDEX idx_courses_department ON Courses(Department_Id);
CREATE INDEX idx_courses_semester   ON Courses(Study_Year, Semester);
CREATE TRIGGER trg_courses_upd
    BEFORE UPDATE ON Courses
    FOR EACH ROW EXECUTE FUNCTION fn_touch_updated_at();


-- SECTION 6 — SESSIONS (specific recurring class meetings)

CREATE TABLE Sessions (
    Session_Id    INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Course_Id     INT          NOT NULL REFERENCES Courses(Course_Id)    ON DELETE RESTRICT,
    Professor_Id  INT          NOT NULL REFERENCES Professors(Professor_Id) ON DELETE RESTRICT,
    Session_Type  session_kind NOT NULL,
    Day_Of_Week   week_day,
    Start_Time    TIME,
    End_Time      TIME,                               -- was missing in original
    Location      VARCHAR(100),
    Semester      semester_type,
    Academic_Year SMALLINT,                           -- calendar year (e.g. 2024 or 2025)
    Created_At    TIMESTAMPTZ  DEFAULT NOW(),
    Updated_At    TIMESTAMPTZ  DEFAULT NOW(),

    CONSTRAINT uq_room_slot UNIQUE NULLS NOT DISTINCT
        (Location, Day_Of_Week, Start_Time, Semester, Academic_Year)
);
CREATE INDEX idx_sessions_course    ON Sessions(Course_Id);
CREATE INDEX idx_sessions_professor ON Sessions(Professor_Id);
CREATE INDEX idx_sessions_schedule  ON Sessions(Day_Of_Week, Start_Time);
CREATE INDEX idx_sessions_semester  ON Sessions(Semester, Academic_Year);
CREATE TRIGGER trg_sessions_upd
    BEFORE UPDATE ON Sessions
    FOR EACH ROW EXECUTE FUNCTION fn_touch_updated_at();


-- SECTION 7 — STUDENT REGISTRATIONS (semester-level confirmation)

CREATE TABLE Student_Registrations (
    Registration_Id   INT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Student_Id        INT           NOT NULL REFERENCES Students(Student_Id) ON DELETE RESTRICT,
    Semester          semester_type NOT NULL,
    Academic_Year     VARCHAR(9)    NOT NULL,          -- e.g. '2024/2025'
    Registration_Date TIMESTAMPTZ   DEFAULT NOW(),
    Status            VARCHAR(20)   NOT NULL DEFAULT 'Active'
                          CHECK (Status IN ('Active','Withdrawn','Suspended')),
    Created_At        TIMESTAMPTZ   DEFAULT NOW(),
    UNIQUE (Student_Id, Semester, Academic_Year)
);
CREATE INDEX idx_student_reg_student  ON Student_Registrations(Student_Id);
CREATE INDEX idx_student_reg_semester ON Student_Registrations(Student_Id, Semester, Academic_Year);


-- SECTION 8 — STUDENT COURSES (course-level enrollment)

CREATE TABLE Student_Courses (
    Student_Id        INT           NOT NULL REFERENCES Students(Student_Id) ON DELETE RESTRICT,
    Course_Id         INT           NOT NULL REFERENCES Courses(Course_Id)   ON DELETE RESTRICT,
    Semester          semester_type NOT NULL,
    Academic_Year     VARCHAR(9)    NOT NULL,           -- e.g. '2024/2025'
    Registration_Date TIMESTAMPTZ   DEFAULT NOW(),
    -- Composite PK was missing in the original schema
    PRIMARY KEY (Student_Id, Course_Id, Semester, Academic_Year)
);
CREATE INDEX idx_student_courses_course   ON Student_Courses(Course_Id);
CREATE INDEX idx_student_courses_semester ON Student_Courses(Student_Id, Semester, Academic_Year);


-- SECTION 9 — ENROLLMENTS (session-level: student ↔ specific session)

CREATE TABLE Enrollments (
    Enrollment_Id INT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Student_Id    INT           NOT NULL REFERENCES Students(Student_Id) ON DELETE RESTRICT,
    Session_Id    INT           NOT NULL REFERENCES Sessions(Session_Id) ON DELETE RESTRICT,
    Semester      semester_type,
    Grade         grade_type,
    Gpa           NUMERIC(3,2)  CHECK (Gpa BETWEEN 0.00 AND 4.00), -- NUMERIC avoids float rounding errors
    Created_At    TIMESTAMPTZ   DEFAULT NOW(),
    Updated_At    TIMESTAMPTZ   DEFAULT NOW(),
    UNIQUE (Student_Id, Session_Id)                    -- no duplicate enrollments
);
CREATE INDEX idx_enrollments_student  ON Enrollments(Student_Id);
CREATE INDEX idx_enrollments_session  ON Enrollments(Session_Id);
CREATE INDEX idx_enrollments_semester ON Enrollments(Student_Id, Semester);
CREATE TRIGGER trg_enrollments_upd
    BEFORE UPDATE ON Enrollments
    FOR EACH ROW EXECUTE FUNCTION fn_touch_updated_at();


-- SECTION 10 — ATTENDANCE

CREATE TABLE Attendance (
    Attendance_Id   INT               GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Student_Id      INT               NOT NULL REFERENCES Students(Student_Id) ON DELETE RESTRICT,
    Session_Id      INT               NOT NULL REFERENCES Sessions(Session_Id) ON DELETE RESTRICT,
    Attendance_Date DATE              NOT NULL DEFAULT CURRENT_DATE,
    Status          attendance_status NOT NULL,
    Check_In_Time   TIME,
    Created_At      TIMESTAMPTZ       DEFAULT NOW(),
    UNIQUE (Student_Id, Session_Id, Attendance_Date)
);
CREATE INDEX idx_attendance_student      ON Attendance(Student_Id);
CREATE INDEX idx_attendance_session      ON Attendance(Session_Id);
CREATE INDEX idx_attendance_date_session ON Attendance(Attendance_Date, Session_Id);
CREATE INDEX idx_attendance_student_date ON Attendance(Student_Id, Attendance_Date DESC);


-- SECTION 11 — FEEDBACK

CREATE TABLE Feedback (
    Feedback_Id  INT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    Student_Id   INT      NOT NULL REFERENCES Students(Student_Id)    ON DELETE RESTRICT,
    Session_Id   INT      NOT NULL REFERENCES Sessions(Session_Id)    ON DELETE RESTRICT,
    Professor_Id INT      NOT NULL REFERENCES Professors(Professor_Id) ON DELETE RESTRICT,
    Rating       SMALLINT NOT NULL CHECK (Rating BETWEEN 1 AND 5),
    Comments     TEXT,
    Created_At   TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (Student_Id, Session_Id)                   
);
CREATE INDEX idx_feedback_student   ON Feedback(Student_Id);
CREATE INDEX idx_feedback_session   ON Feedback(Session_Id);
CREATE INDEX idx_feedback_professor ON Feedback(Professor_Id);


-- SECTION 12 — BOT INTERACTION LOGS

CREATE TABLE Bot_Interaction_Logs (
    Log_Id                INT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Telegram_Chat_Id      BIGINT      NOT NULL,
    Telegram_Username     VARCHAR(100),               -- stored for display; NO FK (usernames change)
    Student_Id            INT         REFERENCES Students(Student_Id) ON DELETE SET NULL,
    Command               VARCHAR(50),                -- e.g. '/schedule', '/grades', '/attendance'
    Message_Received      TEXT,
    Bot_Response          TEXT,
    Response_Time_Ms      INT,                        -- track bot latency for monitoring
    Interaction_Timestamp TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_bot_logs_chat_id   ON Bot_Interaction_Logs(Telegram_Chat_Id);
CREATE INDEX idx_bot_logs_student   ON Bot_Interaction_Logs(Student_Id);
CREATE INDEX idx_bot_logs_timestamp ON Bot_Interaction_Logs(Interaction_Timestamp DESC);
CREATE INDEX idx_bot_logs_command   ON Bot_Interaction_Logs(Command);


-- SECTION 13 — BOT STATES  [NEW TABLE]


CREATE TABLE Bot_States (
    Telegram_Chat_Id BIGINT       NOT NULL PRIMARY KEY,  -- one active state per chat
    Student_Id       INT          REFERENCES Students(Student_Id) ON DELETE CASCADE,
    Current_State    VARCHAR(100) NOT NULL DEFAULT 'IDLE',

    State_Data       JSONB,                             -- flexible payload for multi-step flows
    Last_Updated     TIMESTAMPTZ  DEFAULT NOW(),
    Expires_At       TIMESTAMPTZ  DEFAULT NOW() + INTERVAL '2 hours' -- auto-expire stale sessions
);
CREATE INDEX idx_bot_states_student ON Bot_States(Student_Id);
CREATE INDEX idx_bot_states_expires ON Bot_States(Expires_At);   -- for cleanup cron job
CREATE INDEX idx_bot_states_data    ON Bot_States USING GIN(State_Data); -- for JSONB queries


-- SECTION 14 — UTILITY FUNCTIONS

CREATE OR REPLACE FUNCTION fn_upsert_bot_state(
    p_chat_id    BIGINT,
    p_student_id INT,
    p_state      VARCHAR,
    p_data       JSONB DEFAULT NULL
)
RETURNS VOID LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO Bot_States(Telegram_Chat_Id, Student_Id, Current_State, State_Data)
    VALUES (p_chat_id, p_student_id, p_state, p_data)
    ON CONFLICT (Telegram_Chat_Id) DO UPDATE SET
        Student_Id    = EXCLUDED.Student_Id,
        Current_State = EXCLUDED.Current_State,
        State_Data    = EXCLUDED.State_Data,
        Last_Updated  = NOW(),
        Expires_At    = NOW() + INTERVAL '2 hours';
END;
$$;


CREATE OR REPLACE FUNCTION fn_purge_expired_bot_states()
RETURNS INTEGER LANGUAGE plpgsql AS $$
DECLARE deleted_count INTEGER;
BEGIN
    DELETE FROM Bot_States WHERE Expires_At < NOW();
    GET DIAGNOSTICS deleted_count = ROW_COUNT;
    RETURN deleted_count;
END;
$$;

CREATE OR REPLACE FUNCTION fn_get_student_by_telegram(p_telegram_id BIGINT)
RETURNS TABLE (
    Student_Id   INT,
    Student_Name VARCHAR,
    Study_Year   SMALLINT,
    Is_Active    BOOLEAN
) LANGUAGE sql STABLE AS $$
    SELECT Student_Id, Student_Name, Study_Year, Is_Active
    FROM   Students
    WHERE  Telegram_Id = p_telegram_id
    LIMIT  1;
$$;


-- SECTION 15 — MATERIALIZED VIEW: Student Weekly Schedule


CREATE MATERIALIZED VIEW mv_student_schedule AS
SELECT
    s.Student_Id,
    s.Telegram_Id,
    s.Student_Name,
    c.Course_Code,
    c.Course_Name,
    ses.Session_Id,
    ses.Session_Type,
    ses.Day_Of_Week,
    ses.Start_Time,
    ses.End_Time,
    ses.Location,
    p.Professor_Name,
    e.Semester,
    ses.Academic_Year
FROM   Students      s
JOIN   Enrollments   e   ON s.Student_Id  = e.Student_Id
JOIN   Sessions      ses ON e.Session_Id  = ses.Session_Id
JOIN   Courses       c   ON ses.Course_Id = c.Course_Id
JOIN   Professors    p   ON ses.Professor_Id = p.Professor_Id
WHERE  s.Is_Active = TRUE;

CREATE UNIQUE INDEX idx_mv_schedule_pk
    ON mv_student_schedule(Student_Id, Session_Id);
CREATE INDEX idx_mv_schedule_telegram
    ON mv_student_schedule(Telegram_Id);
CREATE INDEX idx_mv_schedule_day
    ON mv_student_schedule(Telegram_Id, Day_Of_Week, Start_Time);

